version: '3.5'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  test:
    container_name: test
    build: ./build
    command: npm test -- --hostname=selenium
    depends_on:
      - selenium
    volumes:
      - ./specs:/app/test/specs
